//! Generated sources.
//!
//! Two products, and deliberately no more:
//!
//! * `config.rs` — every symbol as a typed constant. Preferred over `--cfg` wherever the value
//!   flows into logic, because a `const` participates in type checking and dead-code elimination
//!   while a `cfg` only deletes text.
//! * `--cfg` / `--check-cfg` flags — for crate- and module-level selection only.
//!
//! `--check-cfg` is emitted for every known symbol, so a typo in a `#[cfg(...)]` is a
//! warning from rustc rather than a silently dead module.

use std::path::{Path, PathBuf};

use crate::kcfg::{Kind, Resolution, SymbolTable, Tri, Val};

#[allow(dead_code)] // config_rs is the path callers may want; cfgs drive the build
pub struct Generated {
    pub config_rs: PathBuf,
    pub cfgs: Vec<String>,
    pub check_cfgs: Vec<String>,
}

/// The build identity a module must match to load into this kernel: the toolchain, the
/// target specification and every configuration symbol's value, as text, so a refusal can
/// name what differs. The format is `kernel/module/src/identity.rs`'s.
pub fn identity_text(
    table: &SymbolTable,
    res: &Resolution,
    toolchain: &str,
    target: &str,
) -> String {
    let mut out =
        format!("kintane-module-identity 1\ntoolchain {toolchain}\ntarget {target}\nconfig\n");
    for name in &table.order {
        out.push_str(&format!("{name}={}\n", res.values[name].display()));
    }
    out
}

/// `identity` is [`identity_text`] for this build. It is written into `config.rs` as
/// `MODULE_IDENTITY` and its hash as `MODULE_IDENTITY_HASH`, which cost nothing in an image
/// that does not read them.
pub fn emit(
    table: &SymbolTable,
    res: &Resolution,
    gen_dir: &Path,
    identity: &str,
) -> Result<Generated, String> {
    std::fs::create_dir_all(gen_dir).map_err(|e| format!("{}: {e}", gen_dir.display()))?;

    let mut out = String::new();
    out.push_str(
        "// Generated by kbuild. Do not edit; do not commit.\n\
         //\n\
         // Every configuration symbol, as a typed constant. Prefer these to #[cfg]:\n\
         // a const takes part in type checking and dead-code elimination, while a cfg\n\
         // only deletes text before the compiler ever sees it.\n\
         #![no_std]\n\
         #![allow(dead_code)]\n\n",
    );

    let mut cfgs = Vec::new();
    // Passing any --check-cfg turns on checking for *every* cfg name, so the ones
    // rustc itself sets must be declared too or they warn. `test` is set by --test
    // in host builds and read by the `cfg_attr(not(test), no_std)` in every kernel
    // crate.
    let mut check_cfgs = vec!["--check-cfg=cfg(test)".to_string()];

    for name in &table.order {
        let sym = &table.symbols[name];
        let val = &res.values[name];

        if let Some(p) = &sym.prompt {
            out.push_str(&format!("/// {p}\n"));
        }
        if let Some(h) = &sym.help {
            for line in h.lines().take(6) {
                out.push_str(&format!("/// {line}\n"));
            }
        }
        out.push_str(&format!("/// * {}\n", res.reasons[name].describe(name)));

        match (sym.kind, val) {
            (Kind::Bool, Val::Tri(t)) => {
                out.push_str(&format!("pub const {name}: bool = {};\n\n", *t != Tri::N));
            }
            (Kind::Tristate, Val::Tri(t)) => {
                // Tristate reaches Rust as an enum so `m` is never silently truthy.
                out.push_str(&format!(
                    "pub const {name}: Tristate = Tristate::{};\n\n",
                    match t {
                        Tri::N => "No",
                        Tri::M => "Module",
                        Tri::Y => "Builtin",
                    }
                ));
            }
            (Kind::Int, Val::Int(i)) => {
                out.push_str(&format!("pub const {name}: usize = {i};\n\n"));
            }
            (Kind::Hex, Val::Hex(h)) => {
                // u64, not usize: an address on a 32-bit target's 64-bit physical bus
                // must survive being generated.
                out.push_str(&format!("pub const {name}: u64 = {h:#x};\n\n"));
            }
            (Kind::Str, Val::Str(s)) => {
                out.push_str(&format!("pub const {name}: &str = {s:?};\n\n"));
            }
            (k, v) => {
                return Err(format!(
                    "internal error: symbol {name} is {} but holds {v:?}",
                    k.name()
                ));
            }
        }

        if matches!(sym.kind, Kind::Bool | Kind::Tristate) {
            check_cfgs.push(format!("--check-cfg=cfg(CONFIG_{name})"));
            if val.is_on() {
                cfgs.push(format!("CONFIG_{name}"));
            }
        }
    }

    out.push_str(
        "#[derive(Clone, Copy, PartialEq, Eq, Debug)]\n\
         pub enum Tristate {\n    No,\n    Module,\n    Builtin,\n}\n\n\
         impl Tristate {\n    \
         pub const fn present(self) -> bool {\n        \
         !matches!(self, Tristate::No)\n    }\n    \
         pub const fn builtin(self) -> bool {\n        \
         matches!(self, Tristate::Builtin)\n    }\n}\n",
    );

    out.push_str(&format!(
        "\n/// This build's identity; see `kbuild/src/codegen.rs`, `identity_text`.\n\
         pub const MODULE_IDENTITY: &str = {identity:?};\n\
         /// SHA-256 of [`MODULE_IDENTITY`].\n\
         pub const MODULE_IDENTITY_HASH: [u8; 32] = {:?};\n",
        crate::sha256::digest(identity.as_bytes())
    ));

    let config_rs = gen_dir.join("config.rs");
    write_if_changed(&config_rs, &out)?;

    Ok(Generated {
        config_rs,
        cfgs,
        check_cfgs,
    })
}

/// Write only when the content differs, so an unchanged regeneration does not
/// invalidate timestamps or confuse a diff between two configurations.
pub fn write_if_changed(path: &Path, content: &str) -> Result<bool, String> {
    if let Ok(existing) = std::fs::read_to_string(path) {
        if existing == content {
            return Ok(false);
        }
    }
    std::fs::write(path, content).map_err(|e| format!("{}: {e}", path.display()))?;
    Ok(true)
}

/// The `.config` file: a complete, explicit record of every symbol's value.
pub fn write_dotconfig(table: &SymbolTable, res: &Resolution, path: &Path) -> Result<(), String> {
    let mut out = String::new();
    out.push_str("# KinTane configuration. Generated by kbuild.\n");
    out.push_str("# Complete and explicit: this plus the source tree is the build.\n\n");
    for name in &table.order {
        let sym = &table.symbols[name];
        let v = &res.values[name];
        match v {
            Val::Tri(Tri::N) => out.push_str(&format!("# {name} is not set\n")),
            _ => out.push_str(&format!("{name}={}\n", v.display())),
        }
        let _ = sym;
    }
    write_if_changed(path, &out)?;
    Ok(())
}

/// Read a `.config` or preset file back into requests.
pub fn read_settings(path: &Path) -> Result<Vec<(String, String)>, String> {
    let src = std::fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
    let mut out = Vec::new();
    for (i, line) in src.lines().enumerate() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let (k, v) = s
            .split_once('=')
            .ok_or_else(|| format!("{}:{}: expected `SYMBOL=value`", path.display(), i + 1))?;
        let v = v.trim();
        let v = v
            .strip_prefix('"')
            .and_then(|r| r.strip_suffix('"'))
            .unwrap_or(v);
        out.push((k.trim().to_string(), v.to_string()));
    }
    Ok(out)
}
