//! Generated sources.
//!
//! Two products, and deliberately no more:
//!
//! * `config.rs` — every symbol as a typed constant. Preferred over `--cfg` wherever the value
//!   flows into logic, because a `const` participates in type checking and dead-code elimination
//!   while a `cfg` only deletes text.
//! * `--cfg` / `--check-cfg` flags — for crate- and module-level selection only.
//!
//! `--check-cfg` is emitted for every known symbol, so a typo in a `#[cfg(...)]` is a
//! warning from rustc rather than a silently dead module.

use std::path::{Path, PathBuf};

use crate::kcfg::{Kind, Resolution, SymbolTable, Tri, Val};

#[allow(dead_code)] // config_rs is the path callers may want; cfgs drive the build
pub struct Generated {
    pub config_rs: PathBuf,
    pub cfgs: Vec<String>,
    pub check_cfgs: Vec<String>,
}

/// The build identity a module must match to load into this kernel: the toolchain, the
/// target specification and every configuration symbol's value, as text, so a refusal can
/// name what differs. The format is `kernel/module/src/identity.rs`'s.
pub fn identity_text(
    table: &SymbolTable,
    res: &Resolution,
    toolchain: &str,
    target: &str,
) -> String {
    let mut out =
        format!("kintane-module-identity 1\ntoolchain {toolchain}\ntarget {target}\nconfig\n");
    for name in &table.order {
        out.push_str(&format!("{name}={}\n", res.values[name].display()));
    }
    out
}

/// The kernel thread-stack array's geometry, derived from the configuration in one place
/// so a linker script and the kernel cannot disagree about it.
///
/// `slots` is what a port's `link.ld` reserves: `KERNEL_THREAD_SLOTS` for threads the
/// scheduler hands out, plus one for every secondary CPU, which takes a stack of its own to
/// come up on and keeps it as its idle thread. A count written into each linker script by
/// hand is what left an eight-CPU stress run with no stack to start its workloads on.
pub struct Stacks {
    /// One slot: the guard at its bottom and the stack above it, in bytes.
    pub slot_bytes: u64,
    /// Slots in the whole array.
    pub slots: u64,
}

/// The geometry this configuration asks for.
pub fn stacks(res: &Resolution) -> Stacks {
    // NR_CPUS has no value without SMP, and a uniprocessor build still has its boot CPU.
    let cpus = if res.is_on("SMP") {
        res.int("NR_CPUS").max(1)
    } else {
        1
    };
    Stacks {
        slot_bytes: res.int("THREAD_STACK_KIB").max(1) as u64 * 1024,
        slots: (res.int("KERNEL_THREAD_SLOTS").max(1) + cpus - 1) as u64,
    }
}

/// The linker fragment every port's `link.ld` includes, so the array it reserves is the one
/// the configuration asked for. It is written beside `config.rs` and found through the `-L`
/// the kernel's link is given.
fn stacks_ld(s: &Stacks) -> String {
    format!(
        "/* Generated by kbuild. Do not edit; do not commit.\n\
         *\n\
         * The kernel thread-stack array, from THREAD_STACK_KIB, KERNEL_THREAD_SLOTS and\n\
         * NR_CPUS. Each `link.ld` includes this rather than naming a count of its own, so\n\
         * the array grows with the CPU count without anyone editing a linker script.\n\
         */\n\
         THREAD_STACK_SLOT = {};\n\
         THREAD_STACK_SLOTS = {};\n",
        s.slot_bytes, s.slots
    )
}

/// `identity` is [`identity_text`] for this build. It is written into `config.rs` as
/// `MODULE_IDENTITY` and its hash as `MODULE_IDENTITY_HASH`, which cost nothing in an image
/// that does not read them.
pub fn emit(
    table: &SymbolTable,
    res: &Resolution,
    gen_dir: &Path,
    identity: &str,
) -> Result<Generated, String> {
    std::fs::create_dir_all(gen_dir).map_err(|e| format!("{}: {e}", gen_dir.display()))?;

    let mut out = String::new();
    out.push_str(
        "// Generated by kbuild. Do not edit; do not commit.\n\
         //\n\
         // Every configuration symbol, as a typed constant. Prefer these to #[cfg]:\n\
         // a const takes part in type checking and dead-code elimination, while a cfg\n\
         // only deletes text before the compiler ever sees it.\n\
         #![no_std]\n\
         #![allow(dead_code)]\n\n",
    );

    let mut cfgs = Vec::new();
    // Passing any --check-cfg turns on checking for *every* cfg name, so the ones
    // rustc itself sets must be declared too or they warn. `test` is set by --test
    // in host builds and read by the `cfg_attr(not(test), no_std)` in every kernel
    // crate.
    let mut check_cfgs = vec!["--check-cfg=cfg(test)".to_string()];

    for name in &table.order {
        let sym = &table.symbols[name];
        let val = &res.values[name];

        if let Some(p) = &sym.prompt {
            out.push_str(&format!("/// {p}\n"));
        }
        if let Some(h) = &sym.help {
            for line in h.lines().take(6) {
                out.push_str(&format!("/// {line}\n"));
            }
        }
        out.push_str(&format!("/// * {}\n", res.reasons[name].describe(name)));

        match (sym.kind, val) {
            (Kind::Bool, Val::Tri(t)) => {
                out.push_str(&format!("pub const {name}: bool = {};\n\n", *t != Tri::N));
            }
            (Kind::Tristate, Val::Tri(t)) => {
                // Tristate reaches Rust as an enum so `m` is never silently truthy.
                out.push_str(&format!(
                    "pub const {name}: Tristate = Tristate::{};\n\n",
                    match t {
                        Tri::N => "No",
                        Tri::M => "Module",
                        Tri::Y => "Builtin",
                    }
                ));
            }
            (Kind::Int, Val::Int(i)) => {
                out.push_str(&format!("pub const {name}: usize = {i};\n\n"));
            }
            (Kind::Hex, Val::Hex(h)) => {
                // u64, not usize: an address on a 32-bit target's 64-bit physical bus
                // must survive being generated.
                out.push_str(&format!("pub const {name}: u64 = {h:#x};\n\n"));
            }
            (Kind::Str, Val::Str(s)) => {
                out.push_str(&format!("pub const {name}: &str = {s:?};\n\n"));
            }
            (k, v) => {
                return Err(format!(
                    "internal error: symbol {name} is {} but holds {v:?}",
                    k.name()
                ));
            }
        }

        if matches!(sym.kind, Kind::Bool | Kind::Tristate) {
            check_cfgs.push(format!("--check-cfg=cfg(CONFIG_{name})"));
            if val.is_on() {
                cfgs.push(format!("CONFIG_{name}"));
            }
        }
    }

    out.push_str(
        "#[derive(Clone, Copy, PartialEq, Eq, Debug)]\n\
         pub enum Tristate {\n    No,\n    Module,\n    Builtin,\n}\n\n\
         impl Tristate {\n    \
         pub const fn present(self) -> bool {\n        \
         !matches!(self, Tristate::No)\n    }\n    \
         pub const fn builtin(self) -> bool {\n        \
         matches!(self, Tristate::Builtin)\n    }\n}\n",
    );

    out.push_str(&format!(
        "\n/// Slots in the kernel thread-stack array every port's `link.ld` reserves, derived\n\
         /// by `codegen::stacks` from THREAD_STACK_KIB's companions KERNEL_THREAD_SLOTS and\n\
         /// NR_CPUS. The same number `stacks.ld` gives the linker, so code sizing a table by\n\
         /// it cannot disagree with the array.\n\
         pub const THREAD_STACK_SLOTS: usize = {};\n",
        stacks(res).slots
    ));

    out.push_str(&format!(
        "\n/// This build's identity; see `kbuild/src/codegen.rs`, `identity_text`.\n\
         pub const MODULE_IDENTITY: &str = {identity:?};\n\
         /// SHA-256 of [`MODULE_IDENTITY`].\n\
         pub const MODULE_IDENTITY_HASH: [u8; 32] = {:?};\n",
        crate::sha256::digest(identity.as_bytes())
    ));

    let config_rs = gen_dir.join("config.rs");
    write_if_changed(&config_rs, &out)?;
    write_if_changed(&gen_dir.join("sizes.ld"), &sizes_ld(table, res))?;
    write_if_changed(&gen_dir.join("stacks.ld"), &stacks_ld(&stacks(res)))?;

    Ok(Generated {
        config_rs,
        cfgs,
        check_cfgs,
    })
}

/// Every numeric symbol as a linker-script assignment, for the sizes a linker script
/// reserves: stacks and the like, which a small machine must be able to shrink.
///
/// A linker script cannot read `.config`, and a section's size is not something the
/// compiler can pass it. So the configuration is emitted in the one language `ld` does
/// read, and a port's script picks what it needs with `INCLUDE sizes.ld`. Numbers only:
/// a string or a bool has no meaning in a script, and the values are unquoted decimal, so
/// a script can do arithmetic with them.
fn sizes_ld(table: &SymbolTable, res: &Resolution) -> String {
    let mut out = String::from(
        "/* Generated by kbuild. Do not edit; do not commit.\n\
         *\n\
         * Every int or hex configuration symbol, for a linker script to size sections\n\
         * with: INCLUDE sizes.ld, then use CONFIG_<NAME>. kbuild puts the directory on\n\
         * the linker's search path for `bin` units. */\n",
    );
    for name in &table.order {
        match res.values[name] {
            Val::Int(i) => out.push_str(&format!("CONFIG_{name} = {i};\n")),
            Val::Hex(h) => out.push_str(&format!("CONFIG_{name} = {h:#x};\n")),
            _ => {}
        }
    }
    out
}

/// Write only when the content differs, so an unchanged regeneration does not
/// invalidate timestamps or confuse a diff between two configurations.
pub fn write_if_changed(path: &Path, content: &str) -> Result<bool, String> {
    if let Ok(existing) = std::fs::read_to_string(path) {
        if existing == content {
            return Ok(false);
        }
    }
    std::fs::write(path, content).map_err(|e| format!("{}: {e}", path.display()))?;
    Ok(true)
}

/// The `.config` file: a complete, explicit record of every symbol's value.
pub fn write_dotconfig(table: &SymbolTable, res: &Resolution, path: &Path) -> Result<(), String> {
    let mut out = String::new();
    out.push_str("# KinTane configuration. Generated by kbuild.\n");
    out.push_str("# Complete and explicit: this plus the source tree is the build.\n\n");
    for name in &table.order {
        let sym = &table.symbols[name];
        let v = &res.values[name];
        match v {
            Val::Tri(Tri::N) => out.push_str(&format!("# {name} is not set\n")),
            _ => out.push_str(&format!("{name}={}\n", v.display())),
        }
        let _ = sym;
    }
    write_if_changed(path, &out)?;
    Ok(())
}

/// Read a `.config` or preset file back into requests.
pub fn read_settings(path: &Path) -> Result<Vec<(String, String)>, String> {
    let src = std::fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
    let mut out = Vec::new();
    for (i, line) in src.lines().enumerate() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let (k, v) = s
            .split_once('=')
            .ok_or_else(|| format!("{}:{}: expected `SYMBOL=value`", path.display(), i + 1))?;
        let v = v.trim();
        let v = v
            .strip_prefix('"')
            .and_then(|r| r.strip_suffix('"'))
            .unwrap_or(v);
        out.push((k.trim().to_string(), v.to_string()));
    }
    Ok(out)
}
